# Generated by Django 3.2.12 on 2022-03-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=64)),
                ('runtime', models.IntegerField()),
                ('rating', models.FloatField()),
                ('overview', models.TextField()),
                ('director', models.CharField(max_length=50)),
            ],
        ),
    ]
