# Generated by Django 3.2.12 on 2022-03-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_film_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='runtime',
            field=models.CharField(max_length=64),
        ),
    ]
