# Generated by Django 3.2.12 on 2022-03-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_film_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
    ]
