# Generated by Django 3.2.12 on 2022-03-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20220330_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='photo',
        ),
    ]
