# Generated by Django 3.2.12 on 2022-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_film_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(max_length=64),
        ),
    ]
