# Generated by Django 3.2.12 on 2022-03-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_film_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='overview',
        ),
        migrations.AlterField(
            model_name='film',
            name='certificate',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='runtime',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
