# Generated by Django 3.2.12 on 2022-03-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20220331_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='photo',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
