# Generated by Django 3.2.12 on 2022-04-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20220331_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='filmpurchase',
            options={'ordering': ['date'], 'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
