# Generated by Django 3.2.12 on 2022-04-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmpurchase',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='FilmLookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
                ('filmID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.film')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
            options={
                'verbose_name': 'Просмотр фильма',
                'verbose_name_plural': 'Просмотры фильмов',
                'ordering': ['datetime'],
            },
        ),
    ]
