# Generated by Django 3.2.12 on 2022-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20220410_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmpurchase',
            name='card',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='filmpurchase',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
